### PR TITLE
show cloudformation events while creating and deleting the stack

### PR DESCRIPTION
**Pull request by ciprianc**

### CODE REVIEW

**Comment by pidah** [comment]
@ciprianc works nicely; can we move get_events and tail functions from fab_tasks into a separate module ?
And add some tests.

**Comment by ashb** [comment]
I think we said that we were happy with this without testing but we just thought it should be in a separate file (was that so the only functions in fab_tasks.py are actual fab tasks?)

**Comment by stuartornum** [comment]
@ashb - yep, thats correct

**Comment by pidah** [comment]
LGTM :+1:

**Comment by pidah** [comment]
reopen

**Pull request merged**
