### PR TITLE
Make sure that set_active_stack activates all ELBs.

### PR DESCRIPTION
**Pull request by kwilczynski**
Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by kwilczynski** [comment]
To be completed:

- [x] Modify `set_active_stack` to work with multiple public ELBs
- [x] Locate other places in the code where `get_first_public_elb()` is also invoked
  - [x] Modify `cfn_delete` to remove DNS entries for all ELBs
  - [x] Modify `get_active_stack` to work with all ELBs
- [x] Handle "dualstack" fully-qualified URLs
- [x] Update unit tests
- [x] Test using single and multiple ELBs stacks

**Comment by kwilczynski** [comment]
@ltsampros @yufangzhang hi there! Please review.

**Comment by kwilczynski** [comment]
More things need to be done in here as per the new requirements from @yufangzhang.

**Comment by ltsampros** [comment]
Looks good to me! @kwilczynski

**Pull request merged**
